"use client";

import Link from "next/link";
import { SectionHeading } from "@/components/ui";

export default function TermsPage() {
  return (
    <div className="max-w-[720px]">
      <header className="mb-12">
        <h1 style={{ fontSize: "var(--text-display)", fontWeight: 700 }}>
          Terms of Service
        </h1>
        <p className="mt-3" style={{ fontSize: "var(--text-sm)", color: "var(--slate)" }}>
          Last updated: September 21, 2026
        </p>
      </header>

      <div className="flex flex-col gap-10" style={{ fontSize: "var(--text-body)", lineHeight: 1.7 }}>

        <section>
          <SectionHeading>1. Agreement</SectionHeading>
          <p>
            By downloading, installing, or using Doppel (&quot;the Software&quot;), you agree to these
            Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Software.
            Doppel is developed and operated by Doppel AI (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
          </p>
        </section>

        <section>
          <SectionHeading>2. Description of service</SectionHeading>
          <p>
            Doppel is a desktop application that observes your screen activity to build a
            personal memory and AI assistant. It runs locally on your machine. An optional
            identity server handles account authentication and billing. An optional MCP
            (Model Context Protocol) server allows external AI agents to query your personal
            memory with your permission.
          </p>
        </section>

        <section>
          <SectionHeading>3. User accounts</SectionHeading>
          <p>
            You may create an account with an email address and password. You are responsible
            for maintaining the security of your account credentials. You must be at least 13
            years old to use Doppel. If you are under 18, you represent that you have your
            parent or guardian&apos;s permission.
          </p>
        </section>

        <section>
          <SectionHeading>4. Plans and payment</SectionHeading>
          <p>
            Doppel offers a free tier with limited daily tokens, a Pro subscription ($20/month)
            with unlimited usage, and pay-as-you-go token packs. Payments are processed through
            Stripe. Subscriptions renew automatically unless canceled. You may cancel at any
            time through the billing page; cancellation takes effect at the end of the current
            billing period. Refunds are handled on a case-by-case basis.
          </p>
        </section>

        <section>
          <SectionHeading>5. Your data</SectionHeading>
          <p>
            Your screen observations, memories, episodes, entities, digests, and user profile
            are stored locally on your machine and are never transmitted to our servers. We do
            not have access to your personal memory data. Your data belongs to you. You can
            export, delete, or wipe your brain at any time.
          </p>
          <p className="mt-3">
            AI processing is performed via third-party APIs (currently Google&apos;s Gemini API).
            Screen content sent to these APIs for processing is subject to their respective
            terms and privacy policies. We do not store or cache API request/response data on
            our servers.
          </p>
        </section>

        <section>
          <SectionHeading>6. Acceptable use</SectionHeading>
          <p>You agree not to:</p>
          <ul className="mt-2" style={{ paddingLeft: 20 }}>
            <li className="mt-1">Use Doppel to monitor other people without their knowledge and consent</li>
            <li className="mt-1">Reverse engineer, decompile, or disassemble the Software beyond what the law permits</li>
            <li className="mt-1">Use the Software to develop competing products</li>
            <li className="mt-1">Circumvent token limits, billing, or license restrictions</li>
            <li className="mt-1">Use the MCP server to expose other people&apos;s data without their consent</li>
            <li className="mt-1">Use the Software for any illegal purpose</li>
          </ul>
        </section>

        <section>
          <SectionHeading>7. Intellectual property</SectionHeading>
          <p>
            The Software, including its code, design, and documentation, is owned by Doppel AI
            and protected by copyright and other intellectual property laws. Your license to
            use the Software is limited to the terms described here.
          </p>
          <p className="mt-3">
            You retain ownership of all data generated by your use of Doppel, including
            memories, episodes, profiles, and any exported brain data.
          </p>
        </section>

        <section>
          <SectionHeading>8. Third-party services</SectionHeading>
          <p>
            Doppel integrates with third-party AI services (Google Gemini API), payment
            processors (Stripe), and optionally with external AI agents via MCP. Your use of
            these services is subject to their respective terms. We are not responsible for
            the availability or conduct of third-party services.
          </p>
        </section>

        <section>
          <SectionHeading>9. Disclaimers</SectionHeading>
          <p>
            THE SOFTWARE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. WE DO NOT WARRANT
            THAT THE SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE. AI-GENERATED
            RESPONSES MAY BE INACCURATE. YOU USE THE SOFTWARE AT YOUR OWN RISK.
          </p>
        </section>

        <section>
          <SectionHeading>10. Limitation of liability</SectionHeading>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, DOPPEL AI SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM
            YOUR USE OF THE SOFTWARE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU
            PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.
          </p>
        </section>

        <section>
          <SectionHeading>11. Changes to terms</SectionHeading>
          <p>
            We may update these Terms from time to time. We will notify you of material
            changes through the Software. Continued use after changes take effect constitutes
            acceptance of the new Terms.
          </p>
        </section>

        <section>
          <SectionHeading>12. Termination</SectionHeading>
          <p>
            You may stop using Doppel at any time by uninstalling the Software. We may
            suspend or terminate your account for violations of these Terms. Upon termination,
            your local data remains on your machine; server-side account data may be deleted
            after 30 days.
          </p>
        </section>

        <section>
          <SectionHeading>13. Contact</SectionHeading>
          <p>
            Questions about these Terms? Contact us at{" "}
            <span style={{ color: "var(--primary)" }}>legal@doppel.ai</span>
          </p>
        </section>

        <div className="mt-4" style={{ fontSize: "var(--text-sm)", color: "var(--slate)" }}>
          <Link href="/privacy" style={{ color: "var(--primary)", textDecoration: "none" }}>
            Privacy Policy
          </Link>
          {" · "}
          <Link href="/billing" style={{ color: "var(--slate)", textDecoration: "none" }}>
            Back to billing
          </Link>
        </div>
      </div>
    </div>
  );
}
